--lsp.preset('recommended')
--lsp.set_preferences({
--  suggest_lsp_servers = true,
--  setup_servers_on_start = true,
--  set_lsp_keymaps = true,
--  configure_diagnostics = true,
--  cmp_capabilities = true,
--  manage_nvim_cmp = true,
--  call_servers = 'local',
--  sign_icons = {
--        error = 'E',
--        warn = 'W',
--        hint = 'H',
--        info = 'I'
--    }
--})
--
--lsp.ensure_installed({
--  'tsserver',
--  'eslint',
--  'sumneko_lua',
--  'pyright',
--  'html',
--  'vimls',
--
--})
--
--lsp.configure('sumneko_lua', {
--    settings = {
--        Lua = {
--            diagnostics = {
--                globals = { 'vim' }
--            }
--        }
--    }
--})
--
--lsp.on_attach(function(client, bufnr)
--  local opts = {buffer = bufnr, remap = false}
--
--  if client.name == "eslint" then
--      vim.cmd.LspStop('eslint')
--      return
--  end
--end)
--
--
--lsp.setup()
